- hosts: localhost
  tasks:
    - name: Create a AI cluster
      karmab.aicli.ai_cluster:
        state: absent
        name: fabien
        parameters:
          network_type: OVNKubernetes
          pull_secret: ~/openshift_pull.json
      register: result
    - debug: var=result
