- hosts: localhost
  tasks:
    - name: Create an AI infraenv
      karmab.aicli.ai_infraenv:
        state: present
        name: biloute
        parameters:
          minimal: true
          pull_secret: ~/openshift_pull.json
      register: result
    - debug: var=result
