- hosts: localhost
  tasks:
    - name: Update host
      karmab.aicli.ai_host:
        state: updated
        name: localhost
        parameters:
          name: myclu
      register: result
    - debug: var=result
