---
- name: create a new env
  ai_infraenv:
    name: "{{ cluster_name }}" 
    state: present
    parameters:
      minimal: true
      pull_secret: ~/openshift_pull.json
  register: result
  tags: infra
- debug: var=result
